### PR TITLE
Upgrading to v0.8.3

### PR DESCRIPTION
**Pull request by polac**
Merged tag v0.8.3 to homeassistant and kept only parts that are essential for using this project as library.

I have done some basic testing against s19 miner.

### CODE REVIEW

**Comment by polac** [comment]
Just noticed that upstream has little bit misleading naming conventions in their tags. v0.8.3-rc1 is actually newer than v0.8.3. Maybe it should have been named as v0.8.4-rc1 (or v0.8.5-rc1 ). @UpstreamData 

So, this doesn't include the latest changes.

**Comment by UpstreamData** [comment]
> Just noticed that upstream has little bit misleading naming conventions in their tags. v0.8.3-rc1 is actually newer than v0.8.3. Maybe it should have been named as v0.8.4-rc1 (or v0.8.5-rc1 ). @UpstreamData 
> 
> 
> 
> So, this doesn't include the latest change

Sorry, I was under the impression that 8.3.0-rc1 would be newer than 8.3.0?  That's my bad, I'm new to this whole releasing software thing.

Either way, I am talking to @Schnitzel in separate channels about properly formatting the base repo and then releasing it as a pip package so I can maintain it and prevent stuff like this.

The main issue is that I'm on vacation right now and away from my computer, and also I have no idea how to release packages to pip.

**Comment by polac** [comment]
Before everything else:  Have a great vacation. These things can wait a little. 

Yes, @Schnitzel has modified your project and released it as package in pypi. I have only updated the latest changes to his branch and maybe at some point it will be packaged and released to pypi. OR you guys come up with some other method. 

 For what it is worth I would suggest migrating to poetry. The whole release process is IMO simpler when using poetry. And it solves the problem you are trying to solve by adding all dependencies to requirements.txt-file a lot cleaner way.
 
 If you guys need help, let me know.

**Comment by UpstreamData** [comment]
Thanks for the suggestion.  I will have to look into poetry.

First order of business is to split off the .tools module as he has done into a separate project, allowing the release to be much smaller and more focused.

Thanks regarding the vacation, but coding doesn't feel much like a job so I don't mind, this is my pet project and I'm happy to work on it when I have access to a computer.

**Comment by UpstreamData** [comment]
I'm working on this right now, got my laptop up and running, so I'm going to try to quickly get this out and running properly.

@Schnitzel I plan to release to PyPi under "miner_interface", this will avoid having to deal with whatever happens if I try to overwrite the package your released (I prefer this naming convention for it anyway)

I will update this thread once I get it up and running as expected so it can be tested as needed.

**Comment by UpstreamData** [comment]
@Schnitzel It shows "miner_interface" as too similar to an existing project.  Could you remove yours from PyPi when you have a chance and I will get this uploaded.

**Comment by polac** [comment]
Closing this for 2 reasons:

- upstream is implementing this already 
- seems like I messed up with merge, so this branch is carbage anyways

**Pull request closed without merging**
